# SwiftLint Configuration for Veloce
# Enforces responsive design patterns and prevents hardcoded dimensions

# Only lint main app files (exclude tests, widgets for now)
included:
  - Veloce

excluded:
  - VeloceTests
  - VeloceUITests
  - VeloceWidgets
  - "**/Preview Content"

# Enabled rules
opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - implicit_return
  - modifier_order
  - overridden_super_call
  - private_action
  - toggle_bool

# Disabled rules (too noisy or not applicable)
disabled_rules:
  - line_length
  - trailing_whitespace
  - opening_brace

# Custom rules for responsive design enforcement
custom_rules:
  # Detect hardcoded frame widths
  hardcoded_frame_width:
    name: "Hardcoded Frame Width"
    regex: '\.frame\(width:\s*\d+[^*]'
    message: "Use ResponsiveLayout values (layout.spacing, layout.orbSize, etc.) instead of hardcoded widths"
    severity: warning
    match_kinds:
      - identifier
      - argument

  # Detect hardcoded frame heights
  hardcoded_frame_height:
    name: "Hardcoded Frame Height"
    regex: '\.frame\(height:\s*\d+[^*]'
    message: "Use ResponsiveLayout values (layout.buttonHeight, layout.inputBarHeight, etc.) instead of hardcoded heights"
    severity: warning
    match_kinds:
      - identifier
      - argument

  # Detect hardcoded font sizes
  hardcoded_font_size:
    name: "Hardcoded Font Size"
    regex: '\.font\(\.system\(size:\s*\d+'
    message: "Use .dynamicTypeFont(base:weight:) for accessibility support"
    severity: warning
    match_kinds:
      - identifier
      - argument

  # Detect hardcoded padding with numbers
  hardcoded_padding:
    name: "Hardcoded Padding"
    regex: '\.padding\(\s*\d+\s*\)'
    message: "Use layout.spacing, layout.screenPadding, or Theme.Spacing tokens"
    severity: warning
    match_kinds:
      - identifier
      - number

  # Detect hardcoded horizontal padding
  hardcoded_horizontal_padding:
    name: "Hardcoded Horizontal Padding"
    regex: '\.padding\(\.horizontal,\s*\d+\)'
    message: "Use layout.screenPadding or layout.spacing"
    severity: warning
    match_kinds:
      - identifier
      - number

  # Detect hardcoded vertical padding
  hardcoded_vertical_padding:
    name: "Hardcoded Vertical Padding"
    regex: '\.padding\(\.vertical,\s*\d+\)'
    message: "Use layout.spacing or layout.cardPadding"
    severity: warning
    match_kinds:
      - identifier
      - number

  # Ensure views use ResponsiveLayout environment
  missing_responsive_layout:
    name: "Missing ResponsiveLayout"
    regex: 'struct\s+\w+:\s*View\s*\{(?:(?!@Environment\(\\\.responsiveLayout\)).)*?\n\s*var\s+body'
    message: "Consider adding @Environment(\\.responsiveLayout) for responsive design"
    severity: warning
    match_kinds:
      - identifier

# Configuration
force_cast: warning
force_try: warning
identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 60
type_name:
  min_length:
    warning: 3
  max_length:
    warning: 50
file_length:
  warning: 500
  error: 1000
function_body_length:
  warning: 60
  error: 100
type_body_length:
  warning: 300
  error: 500
